export const keys = {
  me: ["me"] as const,
  config: ["config"] as const,
  feed: (type: string) => ["feed", type] as const,
  post: (slug: string) => ["post", slug] as const,
  postEdit: (id: string) => ["post-edit", id] as const,
  related: (id: string) => ["related", id] as const,
  revisions: (id: string) => ["revisions", id] as const,
  comments: (postId: string) => ["comments", postId] as const,
  myPosts: (status: string) => ["my-posts", status] as const,
  profile: (username: string) => ["profile", username] as const,
  profilePosts: (username: string) => ["profile-posts", username] as const,
  profileSeries: (username: string) => ["profile-series", username] as const,
  connections: (username: string, kind: string) => ["connections", username, kind] as const,
  suggestions: ["suggestions"] as const,
  tag: (tag: string) => ["tag", tag] as const,
  tagPosts: (tag: string, sort: string) => ["tag-posts", tag, sort] as const,
  trendingTags: ["tags", "trending"] as const,
  popularTags: ["tags", "popular"] as const,
  search: (params: object) => ["search", params] as const,
  bookmarks: (list: string) => ["bookmarks", list] as const,
  collections: ["collections"] as const,
  notifications: (unread: boolean) => ["notifications", unread] as const,
  unread: ["notifications", "unread-count"] as const,
  series: (id: string) => ["series", id] as const,
  mySeries: ["my-series"] as const,
  sessions: ["sessions"] as const,
  reports: (status: string) => ["mod", "reports", status] as const,
  modUsers: (params: object) => ["mod", "users", params] as const,
  analytics: ["mod", "analytics"] as const,
};
